[package]
name = "advent"
version = "0.1.0"
authors = ["Josh Resch <joshresch.cpp@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.9"
log = "0.4"
pancurses = "0.16"
regex = "1"
nom = "7.1"
